### ISSUE TITLE
王勇健 二面作答

### ISSUE THREAD

**Issue by an-Underpriviliged-ZJUer** [QSCTech/2023-spring-round-two#2]
作答题目：第二题作答题目：
[word](https://github.com/QSCTech/2023-spring-round-two/tree/main/word)

注意事项：
代码在[前端](https://github.com/an-Underpriviliged-ZJUer/qsc/tree/main/frontend/index.html)，文档在[readme](https://github.com/an-Underpriviliged-ZJUer/qsc/tree/main/frontend/%E6%80%BB%E7%BB%93.md)

**Comment by 2t7m22d** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2023 春纳二面，预祝您面试顺利。
