### ISSUE TITLE
陈君林 二面作答

### ISSUE THREAD

**Issue by cjlworld** [QSCTech/2023-spring-round-two#3]
作答题目：
[Minecraft Sever（Lite version）](https://github.com/cjlworld/QscSpringR2-McServer) 

注意事项：
- 客户端代码在 [client.go](https://github.com/cjlworld/QscSpringR2-McServer/blob/master/client.go)
- 服务端代码在 [server.go](https://github.com/cjlworld/QscSpringR2-McServer/blob/master/server.go)
- 文档在 [Document.md](https://github.com/cjlworld/QscSpringR2-McServer/blob/master/Document.md)

**Comment by 2t7m22d** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2023 春纳二面，预祝您面试顺利。
