### ISSUE TITLE
张宇  二面作答

### ISSUE THREAD

**Issue by half-dreamer** [QSCTech/2023-spring-round-two#4]
作答题目：
[Minecraft Server (Lite version)](https://github.com/half-dreamer/Minecraft-Server-Lite-version)

注意事项：
源代码在main分支的src文件夹中，分别为Client.cpp和Server.cpp， 文档即为README.md

**Comment by 2t7m22d** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2023 春纳二面，预祝您面试顺利。
