### ISSUE TITLE
田家璇 二面作答

### ISSUE THREAD

**Issue by TianPlusXuan605** [QSCTech/2023-spring-round-two#5]
[mc.webserver](https://github.com/ttjjxx123/mc.webserver)
[mc.client-spring-round-two](https://github.com/ttjjxx123/mc.client-spring-round-two)
第一个是服务器作答题目，第二个是相应的客户端

**Comment by 2t7m22d** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2023 春纳二面，预祝您面试顺利。
