### ISSUE TITLE
许世泓 二面作答

### ISSUE THREAD

**Issue by Xhlorine** [QSCTech/2023-spring-round-two#6]
作答题目：  
[Minecraft Server(Lite version)](https://github.com/XSHchGH/QSCXSH)  
服务端代码在：[MinecraftServer.go](https://github.com/XSHchGH/QSCXSH/blob/main/MinecraftServer.go)  
客户端代码在：[Client.go](https://github.com/XSHchGH/QSCXSH/blob/main/Client.go)  
文档在：[README.md](https://github.com/XSHchGH/QSCXSH/blob/main/README.md)

**Comment by 2t7m22d** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2023 春纳二面，预祝您面试顺利。
